# Generated by Django 4.1.2 on 2022-11-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_of_publication', '-id']},
        ),
    ]
